{{ include "common.service" (dict "service" .Values.services.checkout "context" .Values "release" .Release ) }}
---
{{ include "common.deployment" (dict "service" .Values.services.checkout "context" $ "release" .Release ) }}
---
{{ include "common.ingress" (dict "service" .Values.services.checkout "context" .Values "release" .Release ) }}